version: 2
jobs:
  build: 
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install jupyter sklearn matplotlib numpy tensorflow pandas 
